male(ghaffar).
male(mehmaam).
male(ibtesam).
female(nashra).
female(aqsa).
female(qundeel).
female(bano).
father(ghaffar,mehmaam).
father(ghaffar,ibtesam).
father(ghaffar,aqsa).
father(ghaffar,nashra).
father(ghaffar,qundeel).
mother(bano,mehmaam).
mother(bano,ibtesam).
mother(bano,aqsa).
mother(bano,nashra).
mother(bano,qundeel).
husband(ghaffar,bano).
wife(bano,ghaffar).
brother(X,Y):-father(Z,X),father(Z,Y),male(X).
sister(X,Y):-mother(Z,X),mother(Z,Y),female(X).
wife2(X,Y):-female(X),male(Y),father(Y,Z),mother(X,Z).

